name: Review pull request

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
  pull_request_review:

permissions:
  pull-requests: write
  issues: write

jobs:
  reviewpad-action:
    runs-on: ubuntu-latest
    steps:
      - name: Running reviewpad action 🚀
        uses: reviewpad/action@v3.x
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: reviewpad.yml
